auth_enabled: false

server:
  http_listen_port: 8000

storage:
  trace:
    backend: local
    block:
      encoding: zstd
    wal:
      path: /tmp/tempo/wal
      encoding: none
    local:
      path: /tmp/tempo/blocks
